
services:
  db:
    image: mongo:latest
    container_name: tpgroupedb
    volumes:
      - mongo_data:/data/db
    networks:
      - tp-network
    restart: always

  backend:
    image: mehdirb26/backend:v1
    container_name: tpgrouped-backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - tp-network
    restart: always

  frontend:
    image: mehdirb26/frontend:v1
    container_name: tpgrouped-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - tp-network
    restart: always
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    command: sh -c "npm install && npm start"

networks:
  tp-network:
    driver: bridge

volumes:
  mongo_data:
